### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by ruaraidhmacfarlane** [ruaraidhmacfarlane/skimpy#1]
![screenshot from 2016-01-18 15 10 09](https://cloud.githubusercontent.com/assets/8971646/12394831/295b6548-bdf6-11e5-86ad-09e57c8f4cbc.png)

**Comment by ruaraidhmacfarlane** [comment]
![screenshot from 2016-01-18 15 18 17](https://cloud.githubusercontent.com/assets/8971646/12394952/bdae6da8-bdf6-11e5-8bbe-4412d5d04dfd.png)

**Comment by charlieegan3** [comment]
i do not like this font.

**Comment by ruaraidhmacfarlane** [comment]
Its just the way it was in our white paper, I wasnt going to run through the set up again
